### ISSUE TITLE
When service is reachable from Internet the communication should be encrypted

### ISSUE THREAD

**Issue by sverhoeven** [nlesc-nano/insilico-server#12]
Use [Caddy](https://caddyserver.com/docs/command-line#caddy-reverse-proxy) or [traefik](https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/) to generate the cert for you and proxy everything for you.

**Comment by felipeZ** [comment]
Since I didn't know how `reverse-proxy` works, I am leaving [this article](https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/) for documentation purposes.

**Comment by felipeZ** [comment]
solved via #15
