### ISSUE TITLE
Start services on boot

### ISSUE THREAD

**Issue by sverhoeven** [nlesc-nano/insilico-server#13]
At the moment the [provisioning/start_app.sh](https://github.com/nlesc-nano/insilico-server/blob/master/provisioning/start_app.sh) scripts starts both MongoDB and web service for you in the background. This works fine until the server reboots, because then you will need to run the playbook again.

It would be nicer to use [docker-compose (restart: always)](https://docs.docker.com/compose/compose-file/#restart) or Systemd to define the services and start them on boot of the server.

**Comment by felipeZ** [comment]
solved via #14
